"""add_gender_to_personal_info

Revision ID: 02d1878986e7
Revises: 655b50963fb5
Create Date: 2025-04-27 10:58:16.248927

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d1878986e7'
down_revision = '655b50963fb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_info', sa.Column('gender', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_info', 'gender')
    # ### end Alembic commands ### 