"""auto_migration_1741936534

Revision ID: 09d7952d9958
Revises: 
Create Date: 2025-03-22 10:53:04.938252

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d7952d9958'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_score', sa.Column('candidate_exam_subject_id', sa.String(length=60), nullable=False))
    op.create_foreign_key(None, 'exam_score', 'candidate_exam_subject', ['candidate_exam_subject_id'], ['candidate_exam_subject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_score', type_='foreignkey')
    op.drop_column('exam_score', 'candidate_exam_subject_id')
    # ### end Alembic commands ### 