"""auto_migration_1741936534

Revision ID: 0de586255108
Revises: 982afe1dcb68
Create Date: 2025-03-17 06:54:05.290343

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de586255108'
down_revision = '982afe1dcb68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_exam', sa.Column('payment_status', sa.String(length=50), nullable=True))
    op.add_column('candidate_exam', sa.Column('payment_amount', sa.Float(), nullable=True))
    op.add_column('candidate_exam', sa.Column('exam_location_id', sa.String(length=50), nullable=True))
    op.add_column('candidate_exam', sa.Column('exam_room_id', sa.String(length=50), nullable=True))
    op.add_column('candidate_exam', sa.Column('attendance', sa.Boolean(), nullable=True))
    op.add_column('candidate_exam', sa.Column('attendance_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidate_exam', sa.Column('notes', sa.String(length=500), nullable=True))
    op.add_column('candidate_exam', sa.Column('exam_metadata', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'candidate_exam', 'exam_room', ['exam_room_id'], ['room_id'])
    op.create_foreign_key(None, 'candidate_exam', 'exam_location', ['exam_location_id'], ['location_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate_exam', type_='foreignkey')
    op.drop_constraint(None, 'candidate_exam', type_='foreignkey')
    op.drop_column('candidate_exam', 'exam_metadata')
    op.drop_column('candidate_exam', 'notes')
    op.drop_column('candidate_exam', 'attendance_time')
    op.drop_column('candidate_exam', 'attendance')
    op.drop_column('candidate_exam', 'exam_room_id')
    op.drop_column('candidate_exam', 'exam_location_id')
    op.drop_column('candidate_exam', 'payment_amount')
    op.drop_column('candidate_exam', 'payment_status')
    # ### end Alembic commands ### 