"""auto_migration_1741936534

Revision ID: 1615d9888f7f
Revises: bbccfcbe11dd
Create Date: 2025-03-17 14:22:39.850788

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1615d9888f7f'
down_revision = 'bbccfcbe11dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('subject_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_subject_subject_code'), 'subject', ['subject_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_subject_code'), table_name='subject')
    op.drop_column('subject', 'subject_code')
    # ### end Alembic commands ### 