"""auto_migration_1741936534

Revision ID: 25abcacbb762
Revises: 6a1034915355
Create Date: 2025-03-19 01:03:40.098777

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25abcacbb762'
down_revision = '6a1034915355'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('role_id', sa.String(length=50), nullable=True))
    op.add_column('invitations', sa.Column('revoked', sa.Boolean(), nullable=True))
    op.add_column('invitations', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invitations', sa.Column('revoked_by', sa.String(length=50), nullable=True))
    op.add_column('invitations', sa.Column('revocation_reason', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'invitations', 'users', ['used_by'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invitations', 'users', ['created_by'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invitations', 'users', ['revoked_by'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invitations', 'roles', ['role_id'], ['role_id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('role_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('require_2fa', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('two_factor_secret', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('backup_codes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['role_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_login_ip')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'backup_codes')
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('users', 'two_factor_secret')
    op.drop_column('users', 'require_2fa')
    op.drop_column('users', 'role_id')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'revocation_reason')
    op.drop_column('invitations', 'revoked_by')
    op.drop_column('invitations', 'revoked_at')
    op.drop_column('invitations', 'revoked')
    op.drop_column('invitations', 'role_id')
    # ### end Alembic commands ### 