"""auto_migration_1741936534

Revision ID: 50fb9aa41620
Revises: 6fb0a576c018
Create Date: 2025-03-17 13:31:31.449245

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fb9aa41620'
down_revision = '6fb0a576c018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('degree', 'education_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('degree', sa.Column('education_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ### 