"""temp_check_1741936534

Revision ID: 655b50963fb5
Revises: 
Create Date: 2025-04-27 06:42:09.614542

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655b50963fb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_info', sa.Column('face_embedding', sa.JSON(), nullable=True, comment='Vector đặc trưng khuôn mặt được mã hóa dưới dạng JSON'))
    op.add_column('personal_info', sa.Column('face_embedding_model', sa.String(length=50), nullable=True, comment='Tên mô hình được sử dụng để tạo embedding'))
    op.add_column('personal_info', sa.Column('face_embedding_date', sa.DateTime(timezone=True), nullable=True, comment='Thời điểm tạo embedding'))
    op.add_column('personal_info', sa.Column('face_embedding_source', sa.String(length=20), nullable=True, comment='Nguồn ảnh (id_card, candidate_card, direct_face)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_info', 'face_embedding_source')
    op.drop_column('personal_info', 'face_embedding_date')
    op.drop_column('personal_info', 'face_embedding_model')
    op.drop_column('personal_info', 'face_embedding')
    # ### end Alembic commands ### 