"""auto_migration_1741936534

Revision ID: 6fb0a576c018
Revises: 0de586255108
Create Date: 2025-03-17 07:08:20.383806

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6fb0a576c018'
down_revision = '0de586255108'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('candidate_exam_exam_room_id_fkey', 'candidate_exam', type_='foreignkey')
    op.drop_constraint('candidate_exam_exam_location_id_fkey', 'candidate_exam', type_='foreignkey')
    op.drop_column('candidate_exam', 'exam_location_id')
    op.drop_column('candidate_exam', 'attendance')
    op.drop_column('candidate_exam', 'payment_amount')
    op.drop_column('candidate_exam', 'exam_room_id')
    op.drop_column('candidate_exam', 'payment_status')
    op.drop_column('candidate_exam', 'attendance_time')
    op.drop_column('candidate_exam', 'exam_metadata')
    op.drop_column('candidate_exam', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_exam', sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('candidate_exam', sa.Column('exam_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('candidate_exam', sa.Column('attendance_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('candidate_exam', sa.Column('payment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('candidate_exam', sa.Column('exam_room_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('candidate_exam', sa.Column('payment_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('candidate_exam', sa.Column('attendance', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('candidate_exam', sa.Column('exam_location_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key('candidate_exam_exam_location_id_fkey', 'candidate_exam', 'exam_location', ['exam_location_id'], ['location_id'])
    op.create_foreign_key('candidate_exam_exam_room_id_fkey', 'candidate_exam', 'exam_room', ['exam_room_id'], ['room_id'])
    # ### end Alembic commands ### 