"""auto_migration_1741936534

Revision ID: 75ef5aab0c54
Revises: 814279c2f6be
Create Date: 2025-03-15 07:51:01.686622

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ef5aab0c54'
down_revision = '814279c2f6be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_school_school_id'), 'school', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_school_id'), table_name='school')
    # ### end Alembic commands ### 