"""auto_migration_1741936534

Revision ID: 76871b6e1707
Revises: 50fb9aa41620
Create Date: 2025-03-17 14:06:58.926141

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76871b6e1707'
down_revision = '50fb9aa41620'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_subject', sa.Column('subject_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_subject', 'subject_metadata')
    # ### end Alembic commands ### 