"""auto_migration_1741936534

Revision ID: 7c99ddae0947
Revises: a66af5f7ada4
Create Date: 2025-03-15 08:19:45.648746

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c99ddae0947'
down_revision = 'a66af5f7ada4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_major', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_major', 'is_active')
    # ### end Alembic commands ### 