"""auto_migration_1741936534

Revision ID: 814279c2f6be
Revises: cb5bd9023a33
Create Date: 2025-03-14 20:41:47.964648

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814279c2f6be'
down_revision = 'cb5bd9023a33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('major', 'education_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major', sa.Column('education_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 