"""Update ExamScore model fields

Revision ID: 94f611abed3f
Revises: de2f0765286a
Create Date: 2025-03-17 14:41:41.751662

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94f611abed3f'
down_revision = 'de2f0765286a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_score', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('exam_score', sa.Column('graded_by', sa.String(length=60), nullable=True))
    op.add_column('exam_score', sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exam_score', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('exam_score', sa.Column('score_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('exam_score', 'additional_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_score', sa.Column('additional_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('exam_score', 'score_metadata')
    op.drop_column('exam_score', 'notes')
    op.drop_column('exam_score', 'graded_at')
    op.drop_column('exam_score', 'graded_by')
    op.drop_column('exam_score', 'status')
    # ### end Alembic commands ### 