"""update_exam_location_model_and_mapping

Revision ID: a41252dae38c
Revises: 1a5d13e786d5
Create Date: 2025-03-15 11:22:44.183327

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a41252dae38c'
down_revision = '1a5d13e786d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_location', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('exam_location', sa.Column('state_province', sa.String(length=100), nullable=True))
    op.add_column('exam_location', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('exam_location', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('exam_location', sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('exam_location', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('exam_location_mapping', sa.Column('mapping_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('exam_location_mapping', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('exam_location_mapping', 'additional_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_location_mapping', sa.Column('additional_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('exam_location_mapping', 'is_active')
    op.drop_column('exam_location_mapping', 'mapping_metadata')
    op.drop_column('exam_location', 'is_active')
    op.drop_column('exam_location', 'contact_info')
    op.drop_column('exam_location', 'postal_code')
    op.drop_column('exam_location', 'country')
    op.drop_column('exam_location', 'state_province')
    op.drop_column('exam_location', 'city')
    # ### end Alembic commands ### 