"""auto_migration_1741936534

Revision ID: a66af5f7ada4
Revises: fae986e8c423
Create Date: 2025-03-15 08:14:35.634800

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66af5f7ada4'
down_revision = 'fae986e8c423'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_candidate_credential_credential_id'), 'candidate_credential', ['credential_id'], unique=False)
    op.create_index(op.f('ix_exam_attempt_history_attempt_history_id'), 'exam_attempt_history', ['attempt_history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_attempt_history_attempt_history_id'), table_name='exam_attempt_history')
    op.drop_index(op.f('ix_candidate_credential_credential_id'), table_name='candidate_credential')
    # ### end Alembic commands ### 