"""auto_migration_1741936534

Revision ID: adab600148a2
Revises: 25abcacbb762
Create Date: 2025-03-19 03:30:09.557579

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adab600148a2'
down_revision = '25abcacbb762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ### 