"""auto_migration_1741936534

Revision ID: bbccfcbe11dd
Revises: 76871b6e1707
Create Date: 2025-03-17 14:08:15.447913

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbccfcbe11dd'
down_revision = '76871b6e1707'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_subject', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('exam_subject', sa.Column('passing_score', sa.Float(), nullable=True))
    op.add_column('exam_subject', sa.Column('max_score', sa.Float(), nullable=True))
    op.add_column('exam_subject', sa.Column('is_required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_subject', 'is_required')
    op.drop_column('exam_subject', 'max_score')
    op.drop_column('exam_subject', 'passing_score')
    op.drop_column('exam_subject', 'weight')
    # ### end Alembic commands ### 