"""auto_migration_1741936534

Revision ID: c5d956c1e112
Revises: 601d1855ce13
Create Date: 2025-03-14 19:05:31.113292

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d956c1e112'
down_revision = '601d1855ce13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'education_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('education_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 