"""auto_migration_1741936534

Revision ID: cbc9f224b2eb
Revises: 94f611abed3f
Create Date: 2025-03-17 16:26:09.676280

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc9f224b2eb'
down_revision = '94f611abed3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_review', sa.Column('score_review_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_review', 'score_review_metadata')
    # ### end Alembic commands ### 