"""Add subject_code field to Subject model

Revision ID: de2f0765286a
Revises: 1615d9888f7f
Create Date: 2025-03-17 14:23:56.238427

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2f0765286a'
down_revision = '1615d9888f7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 