"""auto_migration_1741936534

Revision ID: fae986e8c423
Revises: 75ef5aab0c54
Create Date: 2025-03-15 08:10:26.695559

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae986e8c423'
down_revision = '75ef5aab0c54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_achievement_achievement_id'), 'achievement', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_award_award_id'), 'award', ['award_id'], unique=False)
    op.create_index(op.f('ix_candidate_exam_candidate_exam_id'), 'candidate_exam', ['candidate_exam_id'], unique=False)
    op.create_index(op.f('ix_certificate_certificate_id'), 'certificate', ['certificate_id'], unique=False)
    op.create_index(op.f('ix_degree_degree_id'), 'degree', ['degree_id'], unique=False)
    op.create_index(op.f('ix_education_history_education_history_id'), 'education_history', ['education_history_id'], unique=False)
    op.create_index(op.f('ix_education_level_education_level_id'), 'education_level', ['education_level_id'], unique=False)
    op.create_index(op.f('ix_exam_exam_id'), 'exam', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_location_location_id'), 'exam_location', ['location_id'], unique=False)
    op.create_index(op.f('ix_exam_location_mapping_mapping_id'), 'exam_location_mapping', ['mapping_id'], unique=False)
    op.create_index(op.f('ix_exam_room_room_id'), 'exam_room', ['room_id'], unique=False)
    op.create_index(op.f('ix_exam_schedule_exam_schedule_id'), 'exam_schedule', ['exam_schedule_id'], unique=False)
    op.create_index(op.f('ix_exam_score_exam_score_id'), 'exam_score', ['exam_score_id'], unique=False)
    op.create_index(op.f('ix_exam_score_history_history_id'), 'exam_score_history', ['history_id'], unique=False)
    op.create_index(op.f('ix_exam_subject_exam_subject_id'), 'exam_subject', ['exam_subject_id'], unique=False)
    op.create_index(op.f('ix_exam_type_type_id'), 'exam_type', ['type_id'], unique=False)
    op.create_index(op.f('ix_major_major_id'), 'major', ['major_id'], unique=False)
    op.create_index(op.f('ix_management_unit_unit_id'), 'management_unit', ['unit_id'], unique=False)
    op.create_index(op.f('ix_recognition_recognition_id'), 'recognition', ['recognition_id'], unique=False)
    op.create_index(op.f('ix_school_major_school_major_id'), 'school_major', ['school_major_id'], unique=False)
    op.create_index(op.f('ix_score_review_score_review_id'), 'score_review', ['score_review_id'], unique=False)
    op.create_index(op.f('ix_subject_subject_id'), 'subject', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_subject_id'), table_name='subject')
    op.drop_index(op.f('ix_score_review_score_review_id'), table_name='score_review')
    op.drop_index(op.f('ix_school_major_school_major_id'), table_name='school_major')
    op.drop_index(op.f('ix_recognition_recognition_id'), table_name='recognition')
    op.drop_index(op.f('ix_management_unit_unit_id'), table_name='management_unit')
    op.drop_index(op.f('ix_major_major_id'), table_name='major')
    op.drop_index(op.f('ix_exam_type_type_id'), table_name='exam_type')
    op.drop_index(op.f('ix_exam_subject_exam_subject_id'), table_name='exam_subject')
    op.drop_index(op.f('ix_exam_score_history_history_id'), table_name='exam_score_history')
    op.drop_index(op.f('ix_exam_score_exam_score_id'), table_name='exam_score')
    op.drop_index(op.f('ix_exam_schedule_exam_schedule_id'), table_name='exam_schedule')
    op.drop_index(op.f('ix_exam_room_room_id'), table_name='exam_room')
    op.drop_index(op.f('ix_exam_location_mapping_mapping_id'), table_name='exam_location_mapping')
    op.drop_index(op.f('ix_exam_location_location_id'), table_name='exam_location')
    op.drop_index(op.f('ix_exam_exam_id'), table_name='exam')
    op.drop_index(op.f('ix_education_level_education_level_id'), table_name='education_level')
    op.drop_index(op.f('ix_education_history_education_history_id'), table_name='education_history')
    op.drop_index(op.f('ix_degree_degree_id'), table_name='degree')
    op.drop_index(op.f('ix_certificate_certificate_id'), table_name='certificate')
    op.drop_index(op.f('ix_candidate_exam_candidate_exam_id'), table_name='candidate_exam')
    op.drop_index(op.f('ix_award_award_id'), table_name='award')
    op.drop_index(op.f('ix_achievement_achievement_id'), table_name='achievement')
    # ### end Alembic commands ### 