"""auto_migration_1741936534

Revision ID: fce149867ac2
Revises: a41252dae38c
Create Date: 2025-03-15 12:00:30.759217

This is an Alembic migration script template. 
Each migration script is generated from this template and contains:
- Automatically generated metadata about the migration
- Upgrade and downgrade functions to apply or revert database changes
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fce149867ac2'
down_revision = 'a41252dae38c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_room', sa.Column('floor', sa.Integer(), nullable=True))
    op.add_column('exam_room', sa.Column('room_number', sa.String(length=20), nullable=True))
    op.add_column('exam_room', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('exam_room', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('exam_room', sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('exam_room', sa.Column('special_requirements', sa.Text(), nullable=True))
    op.add_column('exam_room', sa.Column('room_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('exam_room', 'additional_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database changes in this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_room', sa.Column('additional_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('exam_room', 'room_metadata')
    op.drop_column('exam_room', 'special_requirements')
    op.drop_column('exam_room', 'equipment')
    op.drop_column('exam_room', 'is_active')
    op.drop_column('exam_room', 'description')
    op.drop_column('exam_room', 'room_number')
    op.drop_column('exam_room', 'floor')
    # ### end Alembic commands ### 